image: docker:latest
services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.vshn.net

puppetci:3:
  script:
    - docker build -t registry.vshn.net/vshn-docker/puppetci:3 -f Dockerfile3 .
    - docker push registry.vshn.net/vshn-docker/puppetci:3
  tags:
    - dockerbuild

puppetci:4:
  script:
    - docker build -t registry.vshn.net/vshn-docker/puppetci:4 -f Dockerfile4 .
    - docker push registry.vshn.net/vshn-docker/puppetci:4
  tags:
    - dockerbuild

